### ISSUE TITLE
Join session in progress redirect to login and then crash

### ISSUE THREAD

**Issue by Eisman111** [eeldev-ue4/EOS_Example#1]
Hello there,

I am encountering a problem running this project using the Epic DevTools. If I invite a player he can join fine, but if he try to join directly using the Social Panel (like suggested here https://eeldev.com/index.php/joining-a-friend/) he gets redirected to the login, If he tried to login it crash. Any suggestion on how to fix this?

We have touched anything in the project beside setting the credentials.

Thanks!

Ps Keep up with the good work! I really like your plugin!

**Comment by huklen** [comment]
Hello,
Can you please include a logfile?

Thanks

**Comment by Eisman111** [comment]
Hello again,

attached you can find the log, so to reproduce it:
1. Login with devtools with one user and create a session (log Draith.log)
2. Login with devtools with another user and on social panel click join session (log Eis.log)
3. You will be redirected to login page, if you try to login again it won't work since you are already logged in (sorry no crash, that was happening because I was trying to log in with first user instead)

Thanks!
[Draith.log](https://github.com/huklen/EOS_Example/files/5540419/Draith.log)
[Eis.log](https://github.com/huklen/EOS_Example/files/5540420/Eis.log)

**Comment by huklen** [comment]
Ahh I see, use the updated example found here:
https://eeldev.com/index.php/joining-a-friend/

The 1.8.0 update hit yesterday so updating all examples and documentation
is taking a bit

Thanks

**Comment by Eisman111** [comment]
Sadly it still doesn't work for me, I just downloaded again master and I can see that I am aligned like in the images but I still get the error, look into Draith2. The plugin is at 1.8.0 version.

Thanks,
Paolo
[Eis2.log](https://github.com/huklen/EOS_Example/files/5540435/Eis2.log)
[Draith2.log](https://github.com/huklen/EOS_Example/files/5540436/Draith2.log)

**Comment by huklen** [comment]
[2020.11.14-09.34.19:525][691]LogNet: Browse:
eoscore.EOS:000225922fac43338e64ceb4b6fc7d55:GameSession:97/Game/Maps/MainMenu

Seems to still be trying to use eoscore. when its suppose to use EOS:...

Double check your console command execution

Thanks

**Comment by Eisman111** [comment]
That works thanks!

I downloaded master so the command was set wrong in there, maybe it's worth to update it there too.

**Comment by huklen** [comment]
Oh you are totally right, I actually forgot to change the example project,
my bad!

It's been updated now, thanks :)

**Comment by Eisman111** [comment]
Thanks!
